services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: CONTACT_RECEIVER_EMAIL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PUBLIC_API_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TOKEN_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
